In [2]:
import numpy as np

a = np.random.randn(5)

print(a)

[-0.0804682   0.80705054  0.79215763 -1.40834262 -0.43542733]


In [4]:
print(a.T)

[-0.0804682   0.80705054  0.79215763 -1.40834262 -0.43542733]


In [5]:
print(np.dot(a,a.T))

3.4583453018343615


In [6]:
a = np.random.randn(5,1)

print(a)

[[ 0.00624081]
 [-0.86539115]
 [-1.54809325]
 [ 1.75876394]
 [-1.66630296]]


In [7]:
print(a.T)

[[ 0.00624081 -0.86539115 -1.54809325  1.75876394 -1.66630296]]


In [8]:
print(np.dot(a,a.T))

[[ 3.89476569e-05 -5.40073812e-03 -9.66134933e-03  1.09761042e-02
  -1.03990732e-02]
 [-5.40073812e-03  7.48901848e-01  1.33970620e+00 -1.52201875e+00
   1.44200384e+00]
 [-9.66134933e-03  1.33970620e+00  2.39659271e+00 -2.72273058e+00
   2.57959237e+00]
 [ 1.09761042e-02 -1.52201875e+00 -2.72273058e+00  3.09325059e+00
  -2.93063356e+00]
 [-1.03990732e-02  1.44200384e+00  2.57959237e+00 -2.93063356e+00
   2.77656557e+00]]
