In [0]:
import numpy as np

In [0]:
def sigmoid(x):
  return 1 / (1 + np.exp(-x))

In [0]:
def sigmoid_derivatives(x):
  return x * (1 - x)

In [0]:
training_inputs = np.array([[0,0,1],
                            [1,1,1],
                            [1,0,1],
                            [0,1,1]])

In [0]:
training_inputs

array([[0, 0, 1],
       [1, 1, 1],
       [1, 0, 1],
       [0, 1, 1]])

In [0]:
training_outputs = np.array([[0,1,1,0]]).T

In [0]:
training_outputs

array([[0],
       [1],
       [1],
       [0]])

In [0]:
np.random.seed(1)

In [0]:
synaptic_weights = 2 * np.random.random((3, 1)) - 1

In [0]:
print('Random starting synaptic weights:')
synaptic_weights

Random starting synaptic weights:


array([[-0.16595599],
       [ 0.44064899],
       [-0.99977125]])

In [0]:
for iteration in range(1):
  input_layer = training_inputs
  outputs = sigmoid(np.dot(input_layer, synaptic_weights))

In [0]:
print('Outputs after training: ')
outputs

Outputs after training: 


array([[0.2689864 ],
       [0.3262757 ],
       [0.23762817],
       [0.36375058]])

In [0]:
for iteration in range(100000):
  input_layer = training_inputs
  outputs = sigmoid(np.dot(input_layer, synaptic_weights))
  error = training_outputs - outputs
  adjustments = error * sigmoid_derivatives(outputs)
  synaptic_weights += np.dot(input_layer.T, adjustments)

In [0]:
print('Synaptic weights after training: ')
synaptic_weights

Synaptic weights after training: 


array([[12.41741972],
       [-0.20410661],
       [-6.00488552]])

In [0]:
print('Outputs after training: ')
outputs

Outputs after training: 


array([[0.00246061],
       [0.99799164],
       [0.99836182],
       [0.00200723]])