In [0]:
import numpy as np

In [0]:
class NeuralNetwork():
  def __init__(self):
    np.random.seed(1)
    self.synaptic_weights = 2 * np.random.random((3,1)) - 1

  def sigmoid(self, x):
    return 1 / (1 + np.exp(-x))

  def sigmoid_derivatives(self, x):
    return x * (1 - x)

  def train(self, training_inputs, training_outputs, training_iterations):
    for iteration in range(training_iterations):
      output = self.think(training_inputs)
      error = training_outputs - output
      adjustments = np.dot(training_inputs.T, error * self.sigmoid_derivatives(output))
      self.synaptic_weights += adjustments

  def think(self, inputs):
    inputs = inputs.astype(float)
    output = self.sigmoid(np.dot(inputs, self.synaptic_weights))
    return output

In [56]:
if __name__ == '__main__':
  neural_network = NeuralNetwork()
  print("Random Synaptic weights: ")
  print(neural_network.synaptic_weights) 

Random Synaptic weights: 
[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]


In [0]:
training_inputs = np.array([[0,0,1],
                            [1,1,1],
                            [1,0,1],
                            [0,1,1]])

In [58]:
training_inputs

array([[0, 0, 1],
       [1, 1, 1],
       [1, 0, 1],
       [0, 1, 1]])

In [0]:
training_outputs = np.array([[0,1,1,0]]).T

In [60]:
training_outputs

array([[0],
       [1],
       [1],
       [0]])

In [0]:
neural_network.train(training_inputs, training_outputs, 100000)

In [63]:
print("Random Synaptic weights after training: ")
print(neural_network.synaptic_weights) 

Random Synaptic weights after training: 
[[12.00870061]
 [-0.2044116 ]
 [-5.8002822 ]]


In [67]:
A = str(input("Input 1: "))
B = str(input("Input 2: "))
C = str(input("Input 3: "))

print('New situation: input data: ', A, B, C)
print('Output: ')
print(neural_network.think(np.array([A, B, C])))

Input 1: 1
Input 2: 0
Input 3: 1
New situation: input data:  1 0 1
Output: 
[0.99799162]
